### ISSUE TITLE
build.sh not building on Raspberry Pi

### ISSUE THREAD

**Issue by Leuli** [Yepkit/ykurcmd#2]
The build script builds hidapi and copies the libhidapi .so files:

cp -fv hidapi/linux/libhidapi-hidraw.so ykurcmd/linux/
...
cp -fv hidapi/libusb/libhidapi-libusb.so ykurcmd/linux/

However, in the makefile, the .so files from ykurcmd/inc are used. This doesn't work because these files are x86, however the Raspberry Pi runs on an ARM architecture.

I changed the lines in build.sh to

cp -fv hidapi/linux/libhidapi-hidraw.so ykurcmd/inc/
...
cp -fv hidapi/libusb/libhidapi-libusb.so ykurcmd/inc/

Then it worked.

Great product btw :)

**Comment by yep1** [comment]
Thanks for the feedback.
